export const GameEvent = {
    NEWGAME: "NEWGAME",
    LEVEL_COMPLETED: "LEVEL_COMPLETE",
    COLLECT_DONE: "COLLECT_DONE",
    LEVEL_FAILED: "LEVEL_FAILED",
    ON_SELECTED: "ON_SELECTED",
    TOGGLE_VIDEO: "TOGGLE_VIDEO"
}